// Auto-generated GIF palette LUT for slot 0
// Generated by gif_compressor.py  (NUM_COLORS=2, IDX_BITS=2)
// Re-run gif_compressor.py with GIF_SLOT=0 or GIF_SLOT=1 to regenerate.

`default_nettype none

module gif_lut_0 (
    input  wire [1:0] color_idx,
    output reg  [1:0] r,
    output reg  [1:0] g,
    output reg  [1:0] b
);
  always @(*) begin
    case (color_idx)
      2'd0: {r, g, b} = 6'b11_11_01;  // RGB8: 220,237,84
      2'd1: {r, g, b} = 6'b10_10_01;  // RGB8: 141,159,76
      2'd2: {r, g, b} = 6'b11_00_11;  // Background (transparent/magenta)
      default: {r, g, b} = 6'b00_00_00;
    endcase
  end
endmodule
